### ISSUE TITLE
Steam: v1.1.1 crashes to desktop

### ISSUE THREAD

**Issue by whosnick** [RyanJGray/aliasIsolation#15]
The newest build [v1.1.1](https://github.com/RyanJGray/aliasIsolation/releases/tag/v1.1.1) crashes to desktop without error message before the title menu appears.

When I switch the aliasisolation.asi with the one from the build before, it works again.

Windows 11, Steam (non-beta)

**Comment by RyanJGray** [comment]
Huh, that is strange, thanks for reporting it.

Let me have a look and see, could I ask what Windows 11 version you're running and the exact NVIDIA driver version (remember you said latest in your other issue, but just want to know in case others have the same issues as you)?

**Comment by whosnick** [comment]
Driver version 527.56
Windows 11 Pro 22H2 Version 10.0.22621.963

**Comment by RyanJGray** [comment]
I've tested the v1.1.1 release on my laptop here, it seems to work fine, hmm, this is a bit strange.

I did mistakenly include a bugfix in v1.1.1 that was supposed to try, and resolve the UI disappearing when you changed the resolution, or windowed mode (because doing that resets some DirectX stuff).

I'll try reverting that change, in case Windows 11 triggers that logic somehow, and re-release v1.1.1, as I was getting crashes when I changed those settings in-game.

**Comment by RyanJGray** [comment]
Published a new release of 1.1.1, could you give it a go and let me know if the crashing is fixed?

**Comment by whosnick** [comment]
It works now, but also with the "old" 1.1.1 build. Let me explain:

I freshly installed Alien Isolation and the resolution was still set to 720p compared to my 4k desktop resolution.
The intro videos and the "disk" loading screen are displayed in the desktop resolution no matter what resolution is set up in the game.
So when I started the game with the old 1.1.1 build, it crashed when trying to change from 4k >720p when going to the title screen.

I then installed the 1.1.0 and was able to change the resoltion to 4k, same as desktop resolution. Then installed the old 1.1.1 again and it loaded to the title screen. But changing the resolution on the game settings will cause crash to desktop.

With the new 1.1.1, it does not crash, but changing the resolution behaves strangly, with a flickery resoltion confirmation screen that does not accept any keyboard input and not applying the resolution correctly until after exiting out and restarting the game.

1.1.0 seems to be most stable in this regard. Hope this helps!

**Comment by RyanJGray** [comment]
Excellent explanation and tests, thanks for testing the various combinations, that helps a ton!

I need to work out a better way of making the new UI handle resolution / windowed mode changes.

Strange you're getting flickering on that confirmation screen, though.
Changing those video settings breaks the new UI (it becomes invisible, but will still take your keyboard input if you hit DELETE, so it might seem like the game itself isn't responding to your input).

I'm thinking of a better way of handling that, at the moment.

**Comment by RyanJGray** [comment]
Hey!

The resolution changing bug has been resolved in v1.1.3, let me know if you run into any other problems :)

Cheers.
