### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by Cloud3ffect** [RyanJGray/aliasIsolation#17]
The issue I'm having has to do with performance. I remember using the old injector version of this mod on my old setup (can't remember which one it was at this point) and remember there being a slight performance hit, just not as big of a performance hit as I'm seeing now on my current system. With the the system I have now I will drop below 60 fps on a regular basis. My in-game graphical settings are maxed out besides what needs to be on/off for the TAA to work. An example would be when you first acquire the flamethrower my system will be sitting around 30-40 fps. If I'm not using this mod in this area I would be getting a locked 120 fps. 

I tried this with my Steam Deck and was able to get it working. The performance on that device stays locked at 60 fps so far. It does have a performance hit, but not as much as I was seeing on my main system.

My Specs are:
Game store - Steam
OS version - Windows 11 Pro 22H2 22624.1470
GPU model - AMD RX 6800 XT
GPU driver and version - AMD 23.3.2
Mod version - v1.1.1

**Comment by RyanJGray** [comment]
> The issue I'm having has to do with performance. I remember using the old injector version of this mod on my old setup (can't remember which one it was at this point) and remember there being a slight performance hit, just not as big of a performance hit as I'm seeing now on my current system. With the the system I have now I will drop below 60 fps on a regular basis. My in-game graphical settings are maxed out besides what needs to be on/off for the TAA to work. An example would be when you first acquire the flamethrower my system will be sitting around 30-40 fps. If I'm not using this mod in this area I would be getting a locked 120 fps.
> 
> I tried this with my Steam Deck and was able to get it working. The performance on that device stays locked at 60 fps so far. It does have a performance hit, but not as much as I was seeing on my main system.
> 
> My Specs are: Game store - Steam OS version - Windows 11 Pro 22H2 22624.1470 GPU model - AMD RX 6800 XT GPU driver and version - AMD 23.3.2 Mod version - v1.1.1

Hey! Thanks for the detailed report.

I have noticed worsening performance with the mod over the past while, so far I've not narrowed down what exactly has made it worse, but I feel like recent driver updates could have made things worse.

People have had similar performance issues recently, one report [AliasIsolation/aliasIsolation#19](https://github.com/aliasIsolation/aliasIsolation/issues/32) talks about a slowdown with AMD cards that was caused in newer (2020+ it seems) driver versions.
I'm going to have to dig around, and do some debugging to see if there's any specific bit of code in the mod, that is slowing the mod down so much.

Anytime I disable the TAA portion of the mod, I get a solid 60FPS no matter the area and how many particle effects there are.

I've tried the mod on two different systems, and get similar performance drops under Valve's Proton layer.

For reference, my main system's specs are:
Game store - Steam
OS version - Manjaro Linux 6.2.8-1
GPU model - NVIDIA RTX 3080 Ti Mobile
GPU driver and version - NVIDIA (Proprietary) 530.41.03
Mod version - v1.1.1

**Comment by RyanJGray** [comment]
## Progress notes
Disabling the TAA, chromatic aberration and pixel shader (sharpening + shadow graphical fixes) passes, makes no major difference to the performance impact.
Disabling the vertex shader pass dramatically improves the performance.

Disabling the CPU-bound jitter calculation makes a dramatic improvement to the mod's performance.
Instead of the FPS dropping from 190 to 23 in large open spaces, it now drops from 190 to 175.

Further investigation is still on-going.

**Comment by RyanJGray** [comment]
I think I've got a decent fix for this, there still is a definite performance impact to the mod, but in the majority of the levels I tried, it hits at least 65 FPS minimum at 1080p.

The mod definitely still needs some more performance fixes, but for the time being I have got it at least playable on my system.

I'll put out a release shortly that'll include the performance fixes, keep an eye out!

**Comment by RyanJGray** [comment]
Major FPS drops resolved in release v1.1.2.

Still some further performance improvements needed, but overall a much smoother experience.

**Comment by Cloud3ffect** [comment]
I've tested it out on the desktop system I've listed in my last post and the performance increase is very apparent. I'm able to play it at 4K maxed out with very good temporal aa. Makes it look really clean. Thanks a lot!

**Comment by RyanJGray** [comment]
> I've tested it out on the desktop system I've listed in my last post and the performance increase is very apparent. I'm able to play it at 4K maxed out with very good temporal aa. Makes it look really clean. Thanks a lot!

No problem! Glad it works much better for you now, enjoy (:
