### ISSUE TITLE
bug: Resolution change block the game

### ISSUE THREAD

**Issue by AnticOwl** [RyanJGray/aliasIsolation#19]
**Describe the bug**
Changing the game on the fly most of the time hang the game.
Leading to a black screen.
When it works, the full screen become windowed and cannot be set to full screen anymore.

I use custom DSR res. 

Image example at 5040x2160
![image](https://github.com/RyanJGray/aliasIsolation/assets/76813232/6e953eb3-ab49-42dd-bc20-d46abd88cb91)

Also forgot to mention the moving shadows (I don't know if it is intentional)

**Setup details**
 - Game store: Steam
 - OS version: Windows 10 22H2 (19045.2965)
 - GPU model: [e.g. NVIDIA RTX 3090
 - GPU driver and version: 535.95
 - Proton version: [Not applicable if you're running Windows]
 - Mod version: 1.1.2

**Additional context**
Mod would be mainly used for screenshooting.

Beside that, the mod is adding A serious boost in image quality! Thanks a lot for this!

**Comment by AnticOwl** [comment]
Here is a little video about both problems

https://github.com/RyanJGray/aliasIsolation/assets/76813232/b9d0d97e-775e-44e4-b89b-a71cffc629a9

**Comment by RyanJGray** [comment]
Hey there, thanks for the report and the video, it's really helpful!

I suspect I know what is causing that shadow flickering you're seeing (not intentional), I'll have a look into it this week.

The resolution bug is odd, I haven't seen that before, does this only happen when you're using DSR?

I'll need to do some poking around to figure that out.

**Comment by AnticOwl** [comment]
Ryan,

I have to admit, I didn't tested with other non custom DSR resolutions.
I will try in a few.
[EDIT: same in non DSR/custom resolutions. Could it also be as I modified LOD/Shadows etc?]

Also, injecting the Cinematic tools after the game start, works perfectly. But I think you knew that :-)

If I need to test something, just let me know!

Cheers

**Comment by AnticOwl** [comment]
Hey, 

Just poking around. Found something about the shadows? 

Cheers
