### ISSUE TITLE
How can I disable chromatic aberration?

### ISSUE THREAD

**Issue by HighPingTek** [RyanJGray/aliasIsolation#22]
How can I disable chromatic aberration?

**Comment by Dicehunter** [comment]
Even though CA needs to be disabled in the options it seems to still be running, I'd love to disable it as it looks horrendous.

**Comment by RyanJGray** [comment]
You should be able to disable it in this fork's in-game UI.

As a quick fix, if you set Chromatic Aberration to `0.0` in the mod's UI (hit DELETE and pause the game to use the UI), it will stop it rendering.

Make sure to hit "Save Settings" to persist your changes.

I can look into adding an option to just completely turn off that rendering feature, which will probably save some FPS.

**Comment by Dicehunter** [comment]
> You should be able to disable it in this fork's in-game UI.
> 
> As a quick fix, if you set Chromatic Aberration to `0.0` in the mod's UI (hit DELETE and pause the game to use the UI), it will stop it rendering.
> 
> Make sure to hit "Save Settings" to persist your changes.
> 
> I can look into adding an option to just completely turn off that rendering feature, which will probably save some FPS.

Didn't know about the ingame option, Thank you very much for the information, No CA makes a huge difference to image quality :)

**Comment by brad86m** [comment]
I can't get the override for CA working via a settings.txt, or via trying to find older asi loader dlls. The in-game UI will not pop up, no matter what.

Currently having to use the original mod, but that has been causing crashing occasionally. A full-proof way of disabling CA would be greatly appreciated when you have the time to do so.

**Comment by RyanJGray** [comment]
> I can't get the override for CA working via a settings.txt, or via trying to find older asi loader dlls. The in-game UI will not pop up, no matter what.
> 
> Currently having to use the original mod, but that has been causing crashing occasionally. A full-proof way of disabling CA would be greatly appreciated when you have the time to do so.

I have some code written locally to try and make this work in a nicer way, I'll have a look into getting this finished off soon. :smile:

**Comment by brad86m** [comment]
> > I can't get the override for CA working via a settings.txt, or via trying to find older asi loader dlls. The in-game UI will not pop up, no matter what.
> > Currently having to use the original mod, but that has been causing crashing occasionally. A full-proof way of disabling CA would be greatly appreciated when you have the time to do so.
> 
> I have some code written locally to try and make this work in a nicer way, I'll have a look into getting this finished off soon. 😄

Awesome. Looking forward to that.

**Comment by RyanJGray** [comment]
Hey! This has been addressed in v1.1.3.

Press `DELETE` while you're in-game and you can now individually toggle on/off sharpening and chromatic aberration :)

Make sure to hit `Save Settings` so it remembers next time you start the game.
