### ISSUE TITLE
bug: Game not launching with mod installed

### ISSUE THREAD

**Issue by tonyissa** [RyanJGray/aliasIsolation#27]
**Describe the bug**
With alias isolation installed the game will not launch. I click launch from steam and I hear a windows alert sound, but the game does not boot up, even though it says I'm in game until I close it from task manager/ steam. Deleteing the files and trying to launch the game works as intended. Anyone have any ideas on how to fix this?

**How to reproduce**
1. Copy mods folder, aliasIsolation.asi to Alien Isolation folder (folder with AI.exe)
2. Go to https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/ and download d3d11.dll (x86), extract the d3d11.dll to the Alien Isolation folder
3. Try to launch game

**Setup details**
 - Game store: Steam
 - OS version: Windows 10 22H2
 - GPU model: RTX 3070
 - GPU driver and version: Latest
 - Mod version: Tried either 1.1.1 or 1.1.2
 - No other mods installed, no other overlays enabled other than Steam overlay

**Comment by tonyissa** [comment]
Okay, I figured the issue out, AI.exe has to be ran as admin on my setup, but doing that solves the issue.

**Comment by RyanJGray** [comment]
Strange it needs admin to work, if you're hearing the windows alert sound it's possible Alias was crashing, it seems like there is/was an issue with Ultimate ASI Loader which I want to figure out.

Good you solved it in any case!

**Comment by tonyissa** [comment]
> Strange it needs admin to work, if you're hearing the windows alert sound it's possible Alias was crashing, it seems like there is/was an issue with Ultimate ASI Loader which I want to figure out.
> 
> Good you solved it in any case!

Actually, as I understand it now, that wasn't the fix. I'm using RivatunerStatisticsServer to limit the framerate to 100fps since the game has audio bugs past 100fps. As it turns out the 'Custom Direct3D support" option was enabled for some reason which was causing the crashes. After turning that off I now can use Rivatuner to limit the FPS and the game doesn't crash, so it's all good now. 

I thought it was the admin permissions but forgot that I turned off Rivatuner during the same test so I couldn't tell what actually fixed it. Also, when I got a crash dump from AliasIsolation, I checked it and it said something about permissions. But yeah it was 100% Rivatuner and not admin perms.

**Comment by RyanJGray** [comment]
> > Strange it needs admin to work, if you're hearing the windows alert sound it's possible Alias was crashing, it seems like there is/was an issue with Ultimate ASI Loader which I want to figure out.
> > Good you solved it in any case!
> 
> Actually, as I understand it now, that wasn't the fix. I'm using RivatunerStatisticsServer to limit the framerate to 100fps since the game has audio bugs past 100fps. As it turns out the 'Custom Direct3D support" option was enabled for some reason which was causing the crashes. After turning that off I now can use Rivatuner to limit the FPS and the game doesn't crash, so it's all good now.
> 
> I thought it was the admin permissions but forgot that I turned off Rivatuner during the same test so I couldn't tell what actually fixed it. Also, when I got a crash dump from AliasIsolation, I checked it and it said something about permissions. But yeah it was 100% Rivatuner and not admin perms.

That makes sense, I'll add a note in the README about this, thanks for the update!

I haven't tried using Rivatuner or any FPS limiter like that personally, but it makes sense it would interfere if it is hooking some Direct3D stuff.
