### ISSUE TITLE
Crash with Epic Games version

### ISSUE THREAD

**Issue by Keith94** [RyanJGray/aliasIsolation#29]
**Describe the bug**
Game crashes at startup

**How to reproduce**
Launch Epic Games version

**Expected behaviour**
No crash

**Setup details**
 - Game store: Epic
 - OS version: Windows 11 Pro 23H2 22631.3527
 - GPU model: 3070 ti mobile
 - GPU driver and version: 552.22
 - Mod version: 1.1.4, 1.1.3

**Additional context**
```
---------------------------
Fatal error
---------------------------
A fatal error was caught by Alias Isolation, and the current process will terminate.
A crash dump has been written to C:\Users\\AppData\Local\Temp\aliasIsolationCrashDump.dmp.
Press Ctrl+C to copy the contents of this message to the clipboard.

 ?? 
aliasIsolation_hookableOverlayRender
aliasIsolation_hookableOverlayRender
aliasIsolation_hookableOverlayRender
aliasIsolation_hookableOverlayRender
aliasIsolation_hookableOverlayRender
aliasIsolation_hookableOverlayRender
aliasIsolation_hookableOverlayRender
aliasIsolation_hookableOverlayRender
aliasIsolation_hookableOverlayRender
aliasIsolation_hookableOverlayRender
RtlIpv6AddressToStringA
RtlDeactivateActivationContextUnsafeFast
LdrShutdownProcess
RtlExitUserProcess
ExitProcess
 ?? 
 ?? 
 ?? 
 ?? 
BaseThreadInitThunk
RtlInitializeExceptionChain
RtlClearBits

---------------------------
OK   
---------------------------
```
[aliasIsolationCrashDump.dmp](https://github.com/RyanJGray/aliasIsolation/files/15139544/aliasIsolationCrashDump.dmp)

**Comment by RyanJGray** [comment]
Hey!

I missed this when it was put up a while ago, sorry about that!

If this is still an issue, I can try using the EGS release and debugging the overlay issues.

From what I've read, the EGS overlay is kind of notorious for causing crashing and weird issues due to it invasively hooking into DirectX games.

A workaround/fix is planned for this

**Comment by Keith94** [comment]
closing in favor of https://github.com/aliasIsolation/aliasIsolation/issues/42
