### ISSUE TITLE
bug: Doesn't work. Am I doing something wrong?

### ISSUE THREAD

**Issue by Eye29** [RyanJGray/aliasIsolation#31]
**Screenshots**
![20240804135658_1](https://github.com/user-attachments/assets/374177cb-f027-4c7b-be18-ebd416432961)
![image](https://github.com/user-attachments/assets/7f82d1ff-64c6-4f50-b4eb-a817402f5636)
![image](https://github.com/user-attachments/assets/18aecd9c-c877-4b8b-b707-36fd10155ecb)

**Setup details**
 - Game store: Steam
 - OS version: Latest stable Windows 10 Home 22H2
 - GPU model: RTX 3080
 - GPU driver and version: Latest game ready diver (560.70)
 - Mod version: Latest

**Additional context**
Came over here from the original file because the GUI would not work either
I am also using the improved graphics mod because they showcased this mod on there so I don't know if that would affect anything

**Comment by RyanJGray** [comment]
Hey! Thanks for checking out the mod.

You seem to be missing the `aliasIsolation.asi` file from the archive included in the download for the mod.

It should be extracted to the same folder as `AI.EXE` in the screenshot you sent (thanks for that!).

You have `d3d11.dll` and the `mods` folder in that folder, which is correct, so adding the `.asi` should make it work.

**Comment by Eye29** [comment]
Thanks so much for the super fast reply!
It worked and it looks great. I was worried that it was going to look like the blurry crap that a ton of AAA games have but it looks fantastic.
Before this I was using DLDSR to fix the problem but I didn't want to have to do that anymore just for power consumption reasons so this is the best solution I have seen out there.
Here's a screenshot now that it is fixed 
![image](https://github.com/user-attachments/assets/d16dbb74-0774-488b-accf-a3638ebbd73f)

**Comment by RyanJGray** [comment]
No worries! Happened to be checking my phone when you sent the issue in. Glad you like it.

It's a great mod, and it was nice to get it working a bit better (also works on Steam Deck now compared to the original 2016 version)!

Still improvements I want to attempt with regards to performance (open spaces can hit the FPS kind of hard compared to the stock game).

I think some more logic could be moved to the shaders to save on CPU usage and make it more efficient.

Hope you enjoy your game!
