### ISSUE TITLE
Not working with proton

### ISSUE THREAD

**Issue by TheoDecarte** [RyanJGray/aliasIsolation#7]
I'm using steam deck with proton ge, i copied all the files, and it's just not working. No errors, the game starts fine, but the aliasing is the same

**Comment by RyanJGray** [comment]
Hey there, thanks for checking out my fork of aliasIsolation!

Ah, I realised that I forgot to put the launch option, that you need for the mod to work, in the instructions at the time, my bad.
Could you try adding this launch option to the game, in Steam: `WINEDLLOVERRIDES="winmm=n,b"`?

**Comment by TheoDecarte** [comment]
Thanks for the prompt reply, WINEDLLOVERRIDES="winmm=n,b" %command% worked

**Comment by RyanJGray** [comment]
> Thanks for the prompt reply, WINEDLLOVERRIDES="winmm=n,b" %command% worked

You're welcome! Let me know if you run into any trouble with the mod, enjoy. (:
