### ISSUE TITLE
Fatal error on startup

### ISSUE THREAD

**Issue by JLAgamer** [RyanJGray/aliasIsolation#8]
After deleting the `aliasIsolationSharedParams.bin` file. I am still getting this error

---------------------------
Fatal error
---------------------------
A fatal error was caught by Alias Isolation, and the current process will terminate.
A crash dump has been written to C:\Users\thesu\AppData\Local\Temp\aliasIsolationCrashDump.dmp.
Press Ctrl+C to copy the contents of this message to the clipboard.

aliasIsolation_hookableOverlayRender

---------------------------
OK   
---------------------------

**Comment by RyanJGray** [comment]
Hey! Thanks for reporting this.
Could I ask, what game store you are playing the game on?
There seems to be an issue with the Epic Games version of the game right now, so I'm not sure if this is related to that.

**Comment by JLAgamer** [comment]
This is with the Steam version of the game.

**Comment by RyanJGray** [comment]
Any chance that you could re-create this crash, and upload your `aliasIsolationCrashDump.dmp` file, from the location in the fatal error popup?
Curious what seems to trigger these `aliasIsolation_hookableOverlayRender` crashes.

Hmm, are you using ReShade or anything else that would inject into the game?
